CREATE TABLE SECURITY
(
    EMPLOYEE_ID NUMBER PRIMARY KEY REFERENCES EMPLOYEES (EMPLOYEE_ID),
	SEC_ID VARCHAR2(20 BYTE),
	SEC_PASSWORD VARCHAR2(10 BYTE),
	SEC_STATUS CHAR(1 BYTE) CHECK (SEC_STATUS IN ('A', 'I'))
)